M48
; DRILL file {KiCad (6.0.5)} date Sat Oct  8 22:42:18 2022
; FORMAT={-:-/ absolute / inch / decimal}
; #@! TF.CreationDate,2022-10-08T22:42:18+08:00
; #@! TF.GenerationSoftware,Kicad,Pcbnew,(6.0.5)
; #@! TF.FileFunction,NonPlated,1,4,NPTH
FMAT,2
INCH
; #@! TA.AperFunction,NonPlated,NPTH,ComponentDrill
T1C0.0866
%
G90
G05
T1
X5.0621Y-3.3376
X5.0621Y-4.1231
X7.5817Y-3.3376
X7.5817Y-4.125
T0
M30
